### PR TITLE
Fix temporary route handling

### PR DESCRIPTION
**Pull request by jochenehret**
* fix for #50
* don't use default domain for temporary route if a specific domain
  is configured
* instead, use the first domain from the app
* delete temporary route after unmapping it

### CODE REVIEW

**Comment by jochenehret** [comment]
We are still clarifying with our legal department if we can accept the DCO [https://github.com/bluemixgaragelondon/cf-blue-green-deploy/blob/master/CONTRIBUTING.md]. Commits will be signed off accordingly.

**Comment by jochenehret** [comment]
DCO 1.1 has been signed.

**Comment by jochenehret** [comment]
We'll evaluate if the change is still needed as there were several new commits regarding domain handling. (And only then try to rebase this change.)

**Comment by holly-cummins** [comment]
Thanks!

**Comment by holgero** [comment]
Hi @holly-cummins : Yes, the problem was still there, so I merged current master with the change and resolved the conflict.
But it seems I broke some checks. I can't see the details, though. Could you please tell me, what is wrong with the change?

**Comment by bluemixgaragelondon** [comment]
@holgero I tried pulling your changes locally and running the tests. I noticed a failure in a test expectation.

On `main_test.go`, line 185 to 189, you must declare the structure `plugin_models.GetApp_RouteSummary`, even though you have declared that you wish to create a slice of them on line 184.

E.g.

```						
expectedRoutes := []plugin_models.GetApp_RouteSummary{
    plugin_models.GetApp_RouteSummary{Host: "host1", Domain: plugin_models.GetApp_DomainFields{Name: "specific.com"}},
    plugin_models.GetApp_RouteSummary{Host: "host2", Domain: plugin_models.GetApp_DomainFields{Name: "specific.com"}},
    plugin_models.GetApp_RouteSummary{Host: "host1", Domain: plugin_models.GetApp_DomainFields{Name: "specific.net"}},
    plugin_models.GetApp_RouteSummary{Host: "host2", Domain: plugin_models.GetApp_DomainFields{Name: "specific.net"}},
}
```

This made the tests pass for me so I would suggest amending your PR with this in mind. This should kick off the PR builder again.

-- Rufus

**Comment by holgero** [comment]
I did what you suggested. Although I have to admit, I don't understand why that should be necessary. Locally the tests run fine and the GoLand IDE even suggested to remove the redundant type declaration after I added it. (Which go version are these tests using? I am on 1.9.2.)

**Comment by bluemixgaragelondon** [comment]
Apologies, yes I was running 1.8.3. Should not be required to add the type declaration. I'm just investigating the PR builder.

**Comment by bluemixgaragelondon** [comment]
We have discussed this PR, the only "non bug fix" in here is deleting the temporary route after unmapping it. In the interests of not leaving pieces of configuration lying around after bgd completes, I will merge this.

Rufus

**Pull request merged**
