### PR TITLE
Add option for specifying manifest file

### LINKED ISSUE #10: [Feature] Allow specifying manifest files
Currently, there is no possibility to explicitly specify a manifest when doing a blue-green deploy. I would like to be able to do something like the following:

```
cf bgd manifest-uat.yml app-name --smok-tests ./smoke_tests.sh
```

This can be worked around by putting the manifest files in separate directories, but that doesn't feel like a great solution, and makes working with them more awkward than it needs to be.

### PR DESCRIPTION
**Pull request by matulko**
Fixes #10

### CODE REVIEW

**Comment by matulko** [comment]
@holly-cummins, any comments on this pr?

**Comment by holly-cummins** [comment]
Hi Martin, thanks very much for the PR (and the reminder!), and apologies for the slow response. I think this looks good, but we've got a couple of concerns about the duplication in main.go. Instead of doing the `NewFlagSet` logic in two places, it would be cleaner to do it in one place and then pass through a struct or the ManifestPath and SmokeTestPath to the CfPlugin initialisation. I think the fact that you had to do it in two places is probably a weakness of how the current code is structured, so cleaning that up would be generally useful. If you're happy to make that adjustment, that would be *great* - otherwise we can do a commit on top of this one.

**Comment by matulko** [comment]
I'd like to help, but can't do it right now, so if you like to fix that, it'd be great. Hope to get some spare time next week, if you want to wait for an update by me.

**Comment by bluemixgaragelondon** [comment]
We'll pick this up and do the add-on commit now.

**Comment by bluemixgaragelondon** [comment]
Now merged! Thanks for the PR.

**Pull request merged**
